-- AlterTable
ALTER TABLE `Lead` ADD COLUMN `aadhar` VARCHAR(191) NULL,
    ADD COLUMN `city` VARCHAR(191) NULL,
    ADD COLUMN `dob` DATETIME(3) NULL,
    ADD COLUMN `gender` VARCHAR(191) NULL,
    ADD COLUMN `pancard` VARCHAR(191) NULL,
    ADD COLUMN `state` VARCHAR(191) NULL;
