-- AlterTable
ALTER TABLE `Lead` ADD COLUMN `doc1Name` VARCHAR(191) NULL,
    ADD COLUMN `doc2Name` VARCHAR(191) NULL,
    ADD COLUMN `doc3Name` VARCHAR(191) NULL,
    ADD COLUMN `doc4Name` VARCHAR(191) NULL,
    ADD COLUMN `otherDoc1` VARCHAR(191) NULL,
    ADD COLUMN `otherDoc2` VARCHAR(191) NULL,
    ADD COLUMN `otherDoc3` VARCHAR(191) NULL,
    ADD COLUMN `otherDoc4` VARCHAR(191) NULL;
