-- AlterTable
ALTER TABLE `Lead` ADD COLUMN `balanceSheetTwoYears` VARCHAR(191) NULL,
    ADD COLUMN `cardNameRequired` VARCHAR(191) NULL,
    ADD COLUMN `ccBankOneYear` VARCHAR(191) NULL,
    ADD COLUMN `coApAadharCardDocument` VARCHAR(191) NULL,
    ADD COLUMN `coApPancardDocument` VARCHAR(191) NULL,
    ADD COLUMN `coApPassportPhoto` VARCHAR(191) NULL,
    ADD COLUMN `coiTwoYears` VARCHAR(191) NULL,
    ADD COLUMN `currentBankOneYear` VARCHAR(191) NULL,
    ADD COLUMN `detailSheet` VARCHAR(191) NULL,
    ADD COLUMN `employmentType` VARCHAR(191) NULL,
    ADD COLUMN `entityType` VARCHAR(191) NULL,
    ADD COLUMN `grossReceipt` VARCHAR(191) NULL,
    ADD COLUMN `gstReturnTwelveMonths` VARCHAR(191) NULL,
    ADD COLUMN `itrTwoYears` VARCHAR(191) NULL,
    ADD COLUMN `odBankOneYear` VARCHAR(191) NULL,
    ADD COLUMN `ownershipProof` VARCHAR(191) NULL,
    ADD COLUMN `primaryBank` VARCHAR(191) NULL,
    ADD COLUMN `profession` VARCHAR(191) NULL,
    ADD COLUMN `profitLossAnnexure` VARCHAR(191) NULL,
    ADD COLUMN `registrationCertificate` VARCHAR(191) NULL,
    ADD COLUMN `runningLoanSheet` VARCHAR(191) NULL,
    ADD COLUMN `taxAuditReport` VARCHAR(191) NULL,
    ADD COLUMN `turnOver` VARCHAR(191) NULL,
    ADD COLUMN `udhyamAadhar` VARCHAR(191) NULL,
    ADD COLUMN `vehicleBrand` VARCHAR(191) NULL,
    ADD COLUMN `vehicleType` VARCHAR(191) NULL;
